// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syslog.proto

package com.vdm.edm.protos;

public interface LogLineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.LogLine)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string timestamp = 2;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>optional string timestamp = 2;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>optional string timestamp = 2;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>optional string hostname = 3;</code>
   * @return Whether the hostname field is set.
   */
  boolean hasHostname();
  /**
   * <code>optional string hostname = 3;</code>
   * @return The hostname.
   */
  java.lang.String getHostname();
  /**
   * <code>optional string hostname = 3;</code>
   * @return The bytes for hostname.
   */
  com.google.protobuf.ByteString
      getHostnameBytes();

  /**
   * <code>optional string application = 5;</code>
   * @return Whether the application field is set.
   */
  boolean hasApplication();
  /**
   * <code>optional string application = 5;</code>
   * @return The application.
   */
  java.lang.String getApplication();
  /**
   * <code>optional string application = 5;</code>
   * @return The bytes for application.
   */
  com.google.protobuf.ByteString
      getApplicationBytes();

  /**
   * <code>optional string process_id = 6;</code>
   * @return Whether the processId field is set.
   */
  boolean hasProcessId();
  /**
   * <code>optional string process_id = 6;</code>
   * @return The processId.
   */
  java.lang.String getProcessId();
  /**
   * <code>optional string process_id = 6;</code>
   * @return The bytes for processId.
   */
  com.google.protobuf.ByteString
      getProcessIdBytes();

  /**
   * <code>optional string message = 7;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>optional string message = 7;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 7;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
