// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syslog.proto

package com.vdm.edm.protos;

public final class SystemLogProtos {
  private SystemLogProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_LogLine_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_LogLine_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_SystemLog_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_SystemLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014syslog.proto\022\010tutorial\"h\n\007LogLine\022\021\n\tt" +
      "imestamp\030\002 \001(\t\022\020\n\010hostname\030\003 \001(\t\022\023\n\013appl" +
      "ication\030\005 \001(\t\022\022\n\nprocess_id\030\006 \001(\t\022\017\n\007mes" +
      "sage\030\007 \001(\t\",\n\tSystemLog\022\037\n\004line\030\001 \003(\0132\021." +
      "tutorial.LogLineB\'\n\022com.vdm.edm.protosB\017" +
      "SystemLogProtosP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_LogLine_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_LogLine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_LogLine_descriptor,
        new java.lang.String[] { "Timestamp", "Hostname", "Application", "ProcessId", "Message", });
    internal_static_tutorial_SystemLog_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_SystemLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_SystemLog_descriptor,
        new java.lang.String[] { "Line", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
