// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syslog.proto

package com.vdm.edm.protos;

/**
 * Protobuf type {@code tutorial.SystemLog}
 */
public final class SystemLog extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.SystemLog)
    SystemLogOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SystemLog.newBuilder() to construct.
  private SystemLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SystemLog() {
    line_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SystemLog();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SystemLog(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              line_ = new java.util.ArrayList<com.vdm.edm.protos.LogLine>();
              mutable_bitField0_ |= 0x00000001;
            }
            line_.add(
                input.readMessage(com.vdm.edm.protos.LogLine.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        line_ = java.util.Collections.unmodifiableList(line_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.vdm.edm.protos.SystemLogProtos.internal_static_tutorial_SystemLog_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.vdm.edm.protos.SystemLogProtos.internal_static_tutorial_SystemLog_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.vdm.edm.protos.SystemLog.class, com.vdm.edm.protos.SystemLog.Builder.class);
  }

  public static final int LINE_FIELD_NUMBER = 1;
  private java.util.List<com.vdm.edm.protos.LogLine> line_;
  /**
   * <code>repeated .tutorial.LogLine line = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.vdm.edm.protos.LogLine> getLineList() {
    return line_;
  }
  /**
   * <code>repeated .tutorial.LogLine line = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.vdm.edm.protos.LogLineOrBuilder> 
      getLineOrBuilderList() {
    return line_;
  }
  /**
   * <code>repeated .tutorial.LogLine line = 1;</code>
   */
  @java.lang.Override
  public int getLineCount() {
    return line_.size();
  }
  /**
   * <code>repeated .tutorial.LogLine line = 1;</code>
   */
  @java.lang.Override
  public com.vdm.edm.protos.LogLine getLine(int index) {
    return line_.get(index);
  }
  /**
   * <code>repeated .tutorial.LogLine line = 1;</code>
   */
  @java.lang.Override
  public com.vdm.edm.protos.LogLineOrBuilder getLineOrBuilder(
      int index) {
    return line_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < line_.size(); i++) {
      output.writeMessage(1, line_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < line_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, line_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.vdm.edm.protos.SystemLog)) {
      return super.equals(obj);
    }
    com.vdm.edm.protos.SystemLog other = (com.vdm.edm.protos.SystemLog) obj;

    if (!getLineList()
        .equals(other.getLineList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLineCount() > 0) {
      hash = (37 * hash) + LINE_FIELD_NUMBER;
      hash = (53 * hash) + getLineList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.vdm.edm.protos.SystemLog parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.vdm.edm.protos.SystemLog parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.vdm.edm.protos.SystemLog parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.vdm.edm.protos.SystemLog parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.vdm.edm.protos.SystemLog parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.vdm.edm.protos.SystemLog parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.vdm.edm.protos.SystemLog parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.vdm.edm.protos.SystemLog parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.vdm.edm.protos.SystemLog parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.vdm.edm.protos.SystemLog parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.vdm.edm.protos.SystemLog parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.vdm.edm.protos.SystemLog parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.vdm.edm.protos.SystemLog prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tutorial.SystemLog}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.SystemLog)
      com.vdm.edm.protos.SystemLogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vdm.edm.protos.SystemLogProtos.internal_static_tutorial_SystemLog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vdm.edm.protos.SystemLogProtos.internal_static_tutorial_SystemLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vdm.edm.protos.SystemLog.class, com.vdm.edm.protos.SystemLog.Builder.class);
    }

    // Construct using com.vdm.edm.protos.SystemLog.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLineFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (lineBuilder_ == null) {
        line_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        lineBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.vdm.edm.protos.SystemLogProtos.internal_static_tutorial_SystemLog_descriptor;
    }

    @java.lang.Override
    public com.vdm.edm.protos.SystemLog getDefaultInstanceForType() {
      return com.vdm.edm.protos.SystemLog.getDefaultInstance();
    }

    @java.lang.Override
    public com.vdm.edm.protos.SystemLog build() {
      com.vdm.edm.protos.SystemLog result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.vdm.edm.protos.SystemLog buildPartial() {
      com.vdm.edm.protos.SystemLog result = new com.vdm.edm.protos.SystemLog(this);
      int from_bitField0_ = bitField0_;
      if (lineBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          line_ = java.util.Collections.unmodifiableList(line_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.line_ = line_;
      } else {
        result.line_ = lineBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.vdm.edm.protos.SystemLog) {
        return mergeFrom((com.vdm.edm.protos.SystemLog)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.vdm.edm.protos.SystemLog other) {
      if (other == com.vdm.edm.protos.SystemLog.getDefaultInstance()) return this;
      if (lineBuilder_ == null) {
        if (!other.line_.isEmpty()) {
          if (line_.isEmpty()) {
            line_ = other.line_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLineIsMutable();
            line_.addAll(other.line_);
          }
          onChanged();
        }
      } else {
        if (!other.line_.isEmpty()) {
          if (lineBuilder_.isEmpty()) {
            lineBuilder_.dispose();
            lineBuilder_ = null;
            line_ = other.line_;
            bitField0_ = (bitField0_ & ~0x00000001);
            lineBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLineFieldBuilder() : null;
          } else {
            lineBuilder_.addAllMessages(other.line_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.vdm.edm.protos.SystemLog parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.vdm.edm.protos.SystemLog) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.vdm.edm.protos.LogLine> line_ =
      java.util.Collections.emptyList();
    private void ensureLineIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        line_ = new java.util.ArrayList<com.vdm.edm.protos.LogLine>(line_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.vdm.edm.protos.LogLine, com.vdm.edm.protos.LogLine.Builder, com.vdm.edm.protos.LogLineOrBuilder> lineBuilder_;

    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public java.util.List<com.vdm.edm.protos.LogLine> getLineList() {
      if (lineBuilder_ == null) {
        return java.util.Collections.unmodifiableList(line_);
      } else {
        return lineBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public int getLineCount() {
      if (lineBuilder_ == null) {
        return line_.size();
      } else {
        return lineBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public com.vdm.edm.protos.LogLine getLine(int index) {
      if (lineBuilder_ == null) {
        return line_.get(index);
      } else {
        return lineBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public Builder setLine(
        int index, com.vdm.edm.protos.LogLine value) {
      if (lineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLineIsMutable();
        line_.set(index, value);
        onChanged();
      } else {
        lineBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public Builder setLine(
        int index, com.vdm.edm.protos.LogLine.Builder builderForValue) {
      if (lineBuilder_ == null) {
        ensureLineIsMutable();
        line_.set(index, builderForValue.build());
        onChanged();
      } else {
        lineBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public Builder addLine(com.vdm.edm.protos.LogLine value) {
      if (lineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLineIsMutable();
        line_.add(value);
        onChanged();
      } else {
        lineBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public Builder addLine(
        int index, com.vdm.edm.protos.LogLine value) {
      if (lineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLineIsMutable();
        line_.add(index, value);
        onChanged();
      } else {
        lineBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public Builder addLine(
        com.vdm.edm.protos.LogLine.Builder builderForValue) {
      if (lineBuilder_ == null) {
        ensureLineIsMutable();
        line_.add(builderForValue.build());
        onChanged();
      } else {
        lineBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public Builder addLine(
        int index, com.vdm.edm.protos.LogLine.Builder builderForValue) {
      if (lineBuilder_ == null) {
        ensureLineIsMutable();
        line_.add(index, builderForValue.build());
        onChanged();
      } else {
        lineBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public Builder addAllLine(
        java.lang.Iterable<? extends com.vdm.edm.protos.LogLine> values) {
      if (lineBuilder_ == null) {
        ensureLineIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, line_);
        onChanged();
      } else {
        lineBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public Builder clearLine() {
      if (lineBuilder_ == null) {
        line_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        lineBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public Builder removeLine(int index) {
      if (lineBuilder_ == null) {
        ensureLineIsMutable();
        line_.remove(index);
        onChanged();
      } else {
        lineBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public com.vdm.edm.protos.LogLine.Builder getLineBuilder(
        int index) {
      return getLineFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public com.vdm.edm.protos.LogLineOrBuilder getLineOrBuilder(
        int index) {
      if (lineBuilder_ == null) {
        return line_.get(index);  } else {
        return lineBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public java.util.List<? extends com.vdm.edm.protos.LogLineOrBuilder> 
         getLineOrBuilderList() {
      if (lineBuilder_ != null) {
        return lineBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(line_);
      }
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public com.vdm.edm.protos.LogLine.Builder addLineBuilder() {
      return getLineFieldBuilder().addBuilder(
          com.vdm.edm.protos.LogLine.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public com.vdm.edm.protos.LogLine.Builder addLineBuilder(
        int index) {
      return getLineFieldBuilder().addBuilder(
          index, com.vdm.edm.protos.LogLine.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.LogLine line = 1;</code>
     */
    public java.util.List<com.vdm.edm.protos.LogLine.Builder> 
         getLineBuilderList() {
      return getLineFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.vdm.edm.protos.LogLine, com.vdm.edm.protos.LogLine.Builder, com.vdm.edm.protos.LogLineOrBuilder> 
        getLineFieldBuilder() {
      if (lineBuilder_ == null) {
        lineBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.vdm.edm.protos.LogLine, com.vdm.edm.protos.LogLine.Builder, com.vdm.edm.protos.LogLineOrBuilder>(
                line_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        line_ = null;
      }
      return lineBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.SystemLog)
  }

  // @@protoc_insertion_point(class_scope:tutorial.SystemLog)
  private static final com.vdm.edm.protos.SystemLog DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.vdm.edm.protos.SystemLog();
  }

  public static com.vdm.edm.protos.SystemLog getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SystemLog>
      PARSER = new com.google.protobuf.AbstractParser<SystemLog>() {
    @java.lang.Override
    public SystemLog parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SystemLog(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SystemLog> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SystemLog> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.vdm.edm.protos.SystemLog getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

