// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syslog.proto

package com.vdm.edm.protos;

public interface SystemLogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.SystemLog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.LogLine line = 1;</code>
   */
  java.util.List<com.vdm.edm.protos.LogLine> 
      getLineList();
  /**
   * <code>repeated .tutorial.LogLine line = 1;</code>
   */
  com.vdm.edm.protos.LogLine getLine(int index);
  /**
   * <code>repeated .tutorial.LogLine line = 1;</code>
   */
  int getLineCount();
  /**
   * <code>repeated .tutorial.LogLine line = 1;</code>
   */
  java.util.List<? extends com.vdm.edm.protos.LogLineOrBuilder> 
      getLineOrBuilderList();
  /**
   * <code>repeated .tutorial.LogLine line = 1;</code>
   */
  com.vdm.edm.protos.LogLineOrBuilder getLineOrBuilder(
      int index);
}
